"""se modifica tabla ItemsCarrito columna cantidad para que el valor por defecto sea igual a 1

Revision ID: 2bfd7802b5ae
Revises: 9f3a1be9c2d1
Create Date: 2026-06-17 17:31:07.122191

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2bfd7802b5ae'
down_revision: str | Sequence[str] | None = '9f3a1be9c2d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_carrito_cliente_id'), 'carrito', type_='unique')
    op.create_index(op.f('ix_carrito_cliente_id'), 'carrito', ['cliente_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrito_cliente_id'), table_name='carrito')
    op.create_unique_constraint(op.f('uq_carrito_cliente_id'), 'carrito', ['cliente_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
