"""Crear tablas iniciales

Revision ID: 8417bf0af09f
Revises:
Create Date: 2026-06-15 20:37:39.085834

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8417bf0af09f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('usuarios', 'es_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'es_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usuarios', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
